// One-command AWS deploy: `npm run deploy`.
//
// Solves the chicken-and-egg where the frontend must be built with the deployed API URL +
// Cognito IDs, which only exist after the stack is deployed:
//   1. Deploy infra WITHOUT a frontend build present, so the empty-bucket upload is skipped
//      and we get the CDK outputs (API URL, Cognito pool/client, CloudFront URL).
//   2. Build the frontend with those production values (pointing at real Cognito + the API
//      Gateway URL — never the local /api or /cognito), bypassing any local .env.local.
//   3. Deploy again → the BucketDeployment uploads the correct build and invalidates the CDN.
//
// Requires AWS credentials configured (as for any `cdk deploy`) and a bootstrapped account.

import { spawn } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const INFRA_DIR = path.join(ROOT, 'apps/infra');
const FRONTEND_DIR = path.join(ROOT, 'apps/frontend');
const DIST_DIR = path.join(FRONTEND_DIR, 'dist');
const STACK_NAME = 'WorkBoardStack';

function log(msg) {
  console.log(`\x1b[36m[deploy]\x1b[0m ${msg}`);
}

function run(cmd, args, opts = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, { stdio: 'inherit', ...opts });
    child.on('error', reject);
    child.on('exit', (code) =>
      code === 0 ? resolve() : reject(new Error(`${cmd} ${args.join(' ')} exited with ${code}`)),
    );
  });
}

async function cdkDeploy(outputsFile) {
  const args = ['cdk', 'deploy', '--all', '--require-approval', 'never'];
  if (outputsFile) args.push('--outputs-file', outputsFile);
  await run('npx', args, { cwd: INFRA_DIR });
}

/** Build the frontend for production, guaranteeing local env files can't leak into the bundle. */
async function buildFrontendForProd(env) {
  // Vite loads .env.local in every mode and it OVERRIDES .env.production — move it aside so the
  // production build can't inherit the local /api + /cognito values.
  const moved = [];
  for (const name of ['.env.local', '.env.production.local']) {
    const p = path.join(FRONTEND_DIR, name);
    if (existsSync(p)) {
      const bak = `${p}.deploy-bak`;
      renameSync(p, bak);
      moved.push([bak, p]);
    }
  }
  const prodEnv = path.join(FRONTEND_DIR, '.env.production');
  writeFileSync(
    prodEnv,
    [
      '# Generated by `npm run deploy` — production build values from CDK outputs.',
      `VITE_API_BASE_URL=${env.apiBaseUrl}`,
      `VITE_COGNITO_USER_POOL_ID=${env.userPoolId}`,
      `VITE_COGNITO_CLIENT_ID=${env.clientId}`,
      // Empty → the app uses real Cognito SRP (no local emulator/proxy).
      'VITE_COGNITO_ENDPOINT=',
      '',
    ].join('\n'),
  );
  try {
    // --skip-nx-cache is essential: Nx doesn't track .env files as inputs, so without it a
    // cached bundle (with stale/local values) would be reused instead of rebuilt.
    await run('npx', ['nx', 'build', 'frontend', '--skip-nx-cache'], { cwd: ROOT });
  } finally {
    rmSync(prodEnv, { force: true });
    for (const [bak, orig] of moved) renameSync(bak, orig);
  }
}

async function main() {
  const outputsFile = path.join(mkdtempSync(path.join(tmpdir(), 'wb-deploy-')), 'outputs.json');

  // 1. First deploy with no build present → skips the (wrong/empty) upload, yields outputs.
  if (existsSync(DIST_DIR)) rmSync(DIST_DIR, { recursive: true, force: true });
  log('deploying infrastructure (pass 1 of 2 — creating/updating API, Cognito, hosting)…');
  await cdkDeploy(outputsFile);

  const outputs = JSON.parse(readFileSync(outputsFile, 'utf8'))[STACK_NAME] ?? {};
  const apiBaseUrl = String(outputs.ApiBaseUrl ?? '').replace(/\/$/, ''); // trim trailing slash
  const userPoolId = outputs.UserPoolId;
  const clientId = outputs.UserPoolClientId;
  const cloudFrontUrl = outputs.CloudFrontUrl;
  if (!apiBaseUrl || !userPoolId || !clientId) {
    throw new Error(`Missing stack outputs (got ${JSON.stringify(outputs)})`);
  }
  log(`resolved outputs → API ${apiBaseUrl}, pool ${userPoolId}`);

  // 2. Build the frontend against the real, deployed values.
  log('building frontend with production config…');
  await buildFrontendForProd({ apiBaseUrl, userPoolId, clientId });

  // 3. Second deploy uploads the built site and invalidates CloudFront.
  log('deploying infrastructure (pass 2 of 2 — uploading site + invalidating CDN)…');
  await cdkDeploy();

  log(`done → ${cloudFrontUrl}`);
}

main().catch((err) => {
  console.error('\n`npm run deploy` failed:', err.message ?? err);
  process.exit(1);
});
