// One-command fully-local dev: `npm run local`.
//
// Brings up the local backing services (DynamoDB Local + cognito-local) in Docker, creates
// the DynamoDB table, seeds the Cognito pool/client, writes the local .env files from the
// resolved values, then runs the backend and frontend concurrently. No AWS account/creds.
//
// Ctrl+C stops the backend + frontend; the Docker containers are left running for fast
// restarts (stop them with `npm run local:down`).

import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import net from 'node:net';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { bootstrapDynamo } from './bootstrap-dynamo.mjs';
import { seedCognito } from './seed-cognito.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const COMPOSE_FILE = 'apps/backend/docker-compose.yml';
const COGNITO_DIR = path.join(ROOT, 'apps/backend/.cognito');

const DYNAMO_ENDPOINT = 'http://localhost:8000';
const COGNITO_ENDPOINT = 'http://localhost:9229';

function log(msg) {
  console.log(`\x1b[36m[local]\x1b[0m ${msg}`);
}

/** Run a command to completion, inheriting stdio. Rejects on non-zero exit. */
function run(cmd, args, opts = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, { cwd: ROOT, stdio: 'inherit', ...opts });
    child.on('error', reject);
    child.on('exit', (code) =>
      code === 0 ? resolve() : reject(new Error(`${cmd} ${args.join(' ')} exited with ${code}`)),
    );
  });
}

/** Resolve once a TCP port accepts connections, or reject after `timeoutMs`. */
function waitForPort(host, port, timeoutMs = 60_000) {
  const deadline = Date.now() + timeoutMs;
  return new Promise((resolve, reject) => {
    const attempt = () => {
      const socket = net.createConnection({ host, port });
      socket.once('connect', () => {
        socket.destroy();
        resolve();
      });
      socket.once('error', () => {
        socket.destroy();
        if (Date.now() > deadline) reject(new Error(`Timed out waiting for ${host}:${port}`));
        else setTimeout(attempt, 500);
      });
    };
    attempt();
  });
}

/** Retry an async fn with a fixed delay until it succeeds or attempts run out. */
async function retry(fn, attempts = 20, delayMs = 500) {
  let lastErr;
  for (let i = 0; i < attempts; i++) {
    try {
      return await fn();
    } catch (err) {
      lastErr = err;
      await new Promise((r) => setTimeout(r, delayMs));
    }
  }
  throw lastErr;
}

function writeEnvFile(relPath, lines) {
  const full = path.join(ROOT, relPath);
  const header = `# Generated by \`npm run local\` (tools/scripts/dev-local.mjs). Local dev only — do not commit.\n`;
  writeFileSync(full, header + lines.join('\n') + '\n');
  log(`wrote ${relPath}`);
}

/** Stream a child process's stdout/stderr with a colored prefix. */
function streamChild(name, color, child) {
  const prefix = `\x1b[${color}m[${name}]\x1b[0m `;
  const pipe = (stream, sink) => {
    let buf = '';
    stream.on('data', (chunk) => {
      buf += chunk.toString();
      const parts = buf.split('\n');
      buf = parts.pop() ?? '';
      for (const line of parts) sink.write(prefix + line + '\n');
    });
  };
  pipe(child.stdout, process.stdout);
  pipe(child.stderr, process.stderr);
}

async function main() {
  // cognito-local needs its config dir + config.json before the container starts. Pin the
  // token IssuerDomain to the localhost endpoint so issued tokens carry a stable `iss` that
  // matches the backend verifier + the JWKS host (its default is http://0.0.0.0:9229, which
  // the backend can't match). Read only at container start — see README if you change it.
  if (!existsSync(COGNITO_DIR)) mkdirSync(COGNITO_DIR, { recursive: true });
  const cfg = path.join(COGNITO_DIR, 'config.json');
  writeFileSync(cfg, JSON.stringify({ TokenConfig: { IssuerDomain: COGNITO_ENDPOINT } }, null, 2) + '\n');

  // 1. Verify Docker is available.
  try {
    await run('docker', ['--version'], { stdio: 'ignore' });
  } catch {
    console.error('\nDocker is required for `npm run local` (DynamoDB Local + cognito-local).');
    console.error('Install/start Docker Desktop and re-run. See README → Local development.\n');
    process.exit(1);
  }

  // 2. Start the backing services.
  log('starting Docker services (DynamoDB Local + cognito-local)…');
  await run('docker', ['compose', '-f', COMPOSE_FILE, 'up', '-d']);

  // 3. Wait for both to accept connections.
  log('waiting for DynamoDB Local (:8000) and cognito-local (:9229)…');
  await Promise.all([waitForPort('localhost', 8000), waitForPort('localhost', 9229)]);

  // 4. Create the DynamoDB table (in-memory → recreated every start).
  const { tableName, created } = await retry(() => bootstrapDynamo({ endpoint: DYNAMO_ENDPOINT }));
  log(`DynamoDB table "${tableName}" ${created ? 'created' : 'ready'}.`);

  // 5. Seed the Cognito pool/client (idempotent) and capture the local IDs.
  const { userPoolId, clientId, issuer, jwksUri } = await retry(() =>
    seedCognito({ endpoint: COGNITO_ENDPOINT }),
  );
  log(`cognito-local ready (pool ${userPoolId}, client ${clientId}).`);

  // 6. Write the local .env files so backend + frontend pick up the resolved config.
  writeEnvFile('apps/backend/.env', [
    'AWS_REGION=us-east-1',
    `WORKBOARD_TABLE_NAME=${tableName}`,
    `DYNAMODB_ENDPOINT=${DYNAMO_ENDPOINT}`,
    'PORT=3000',
    `COGNITO_USER_POOL_ID=${userPoolId}`,
    `COGNITO_CLIENT_ID=${clientId}`,
    'AUTH_LOCAL_VERIFY=true',
    `COGNITO_ISSUER=${issuer}`,
    `COGNITO_JWKS_URI=${jwksUri}`,
  ]);
  writeEnvFile('apps/frontend/.env.local', [
    'VITE_API_BASE_URL=/api',
    `VITE_COGNITO_USER_POOL_ID=${userPoolId}`,
    `VITE_COGNITO_CLIENT_ID=${clientId}`,
    'VITE_COGNITO_ENDPOINT=/cognito',
  ]);

  // 7. Run backend + frontend concurrently.
  log('starting backend (:3000) and frontend (:4200)…\n');
  const children = [
    spawn('npx', ['nx', 'serve', 'backend'], { cwd: ROOT }),
    spawn('npx', ['nx', 'serve', 'frontend'], { cwd: ROOT }),
  ];
  streamChild('backend', '33', children[0]);
  streamChild('frontend', '35', children[1]);

  let shuttingDown = false;
  const shutdown = () => {
    if (shuttingDown) return;
    shuttingDown = true;
    log('shutting down backend + frontend (containers left running — `npm run local:down` to stop them)…');
    for (const c of children) c.kill('SIGTERM');
    setTimeout(() => process.exit(0), 500);
  };
  process.on('SIGINT', shutdown);
  process.on('SIGTERM', shutdown);
  for (const c of children) {
    c.on('exit', (code) => {
      if (!shuttingDown) {
        console.error(`\nA dev process exited (code ${code}); stopping the others.`);
        shutdown();
      }
    });
  }

  log('ready → open http://localhost:4200  (verification code for local sign-up: 123456)');
}

main().catch((err) => {
  console.error('\n`npm run local` failed:', err.message ?? err);
  process.exit(1);
});
