// Prepare the fully-local backing stack for tests / tooling — WITHOUT starting the backend
// or frontend (unlike `npm run local`, which also serves them). Brings up the Docker
// services (DynamoDB Local + cognito-local), creates the table, seeds the Cognito
// pool/client, and writes the local `.env` files so `nx serve backend` / `vite` pick up the
// resolved config. Idempotent — safe to run when the stack is already up.
//
// Used by the Playwright e2e run (`npm run e2e:local`) so `E2E_LOCAL=1` e2e has real auth +
// persistence with no AWS account. Can also be run directly: `node tools/scripts/local-stack.mjs`.

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import net from 'node:net';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { bootstrapDynamo } from './bootstrap-dynamo.mjs';
import { bootstrapS3 } from './bootstrap-s3.mjs';
import { seedCognito } from './seed-cognito.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const COMPOSE_FILE = 'apps/backend/docker-compose.yml';
const COGNITO_DIR = path.join(ROOT, 'apps/backend/.cognito');
const DYNAMO_ENDPOINT = 'http://localhost:8000';
const COGNITO_ENDPOINT = 'http://localhost:9229';
const S3_ENDPOINT = 'http://localhost:4566';
const NOTES_BUCKET = 'workboard-notes-local';

function log(msg) {
  console.log(`\x1b[36m[local-stack]\x1b[0m ${msg}`);
}

function run(cmd, args, opts = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, { cwd: ROOT, stdio: 'inherit', ...opts });
    child.on('error', reject);
    child.on('exit', (code) =>
      code === 0 ? resolve() : reject(new Error(`${cmd} ${args.join(' ')} exited with ${code}`)),
    );
  });
}

function waitForPort(host, port, timeoutMs = 60_000) {
  const deadline = Date.now() + timeoutMs;
  return new Promise((resolve, reject) => {
    const attempt = () => {
      const socket = net.createConnection({ host, port });
      socket.once('connect', () => {
        socket.destroy();
        resolve();
      });
      socket.once('error', () => {
        socket.destroy();
        if (Date.now() > deadline) reject(new Error(`Timed out waiting for ${host}:${port}`));
        else setTimeout(attempt, 500);
      });
    };
    attempt();
  });
}

async function retry(fn, attempts = 20, delayMs = 500) {
  let lastErr;
  for (let i = 0; i < attempts; i++) {
    try {
      return await fn();
    } catch (err) {
      lastErr = err;
      await new Promise((r) => setTimeout(r, delayMs));
    }
  }
  throw lastErr;
}

function writeEnvFile(relPath, lines) {
  const header = `# Generated by tools/scripts/local-stack.mjs. Local dev/e2e only — do not commit.\n`;
  writeFileSync(path.join(ROOT, relPath), header + lines.join('\n') + '\n');
  log(`wrote ${relPath}`);
}

/** Bring up the local stack and write env files. Returns the resolved local IDs. */
export async function prepareLocalStack() {
  // cognito-local needs its config dir + config.json before the container starts (pins the
  // token issuer to the localhost endpoint the backend verifier + JWKS host expect).
  if (!existsSync(COGNITO_DIR)) mkdirSync(COGNITO_DIR, { recursive: true });
  writeFileSync(
    path.join(COGNITO_DIR, 'config.json'),
    JSON.stringify({ TokenConfig: { IssuerDomain: COGNITO_ENDPOINT } }, null, 2) + '\n',
  );

  try {
    await run('docker', ['--version'], { stdio: 'ignore' });
  } catch {
    throw new Error('Docker is required for the local stack. Start Docker Desktop and retry.');
  }

  log('starting Docker services (DynamoDB Local + cognito-local)…');
  await run('docker', ['compose', '-f', COMPOSE_FILE, 'up', '-d']);

  log('waiting for DynamoDB Local (:8000), cognito-local (:9229), LocalStack S3 (:4566)…');
  await Promise.all([
    waitForPort('localhost', 8000),
    waitForPort('localhost', 9229),
    waitForPort('localhost', 4566),
  ]);

  const { tableName, created } = await retry(() => bootstrapDynamo({ endpoint: DYNAMO_ENDPOINT }));
  log(`DynamoDB table "${tableName}" ${created ? 'created' : 'ready'}.`);

  const { bucket, created: bucketCreated } = await retry(() =>
    bootstrapS3({ endpoint: S3_ENDPOINT, bucket: NOTES_BUCKET }),
  );
  log(`LocalStack S3 bucket "${bucket}" ${bucketCreated ? 'created' : 'ready'}.`);

  const { userPoolId, clientId, issuer, jwksUri } = await retry(() =>
    seedCognito({ endpoint: COGNITO_ENDPOINT }),
  );
  log(`cognito-local ready (pool ${userPoolId}, client ${clientId}).`);

  writeEnvFile('apps/backend/.env', [
    'AWS_REGION=us-east-1',
    `WORKBOARD_TABLE_NAME=${tableName}`,
    `DYNAMODB_ENDPOINT=${DYNAMO_ENDPOINT}`,
    `WORKBOARD_NOTES_BUCKET=${bucket}`,
    `S3_ENDPOINT=${S3_ENDPOINT}`,
    'S3_FORCE_PATH_STYLE=true',
    'PORT=3000',
    `COGNITO_USER_POOL_ID=${userPoolId}`,
    `COGNITO_CLIENT_ID=${clientId}`,
    'AUTH_LOCAL_VERIFY=true',
    `COGNITO_ISSUER=${issuer}`,
    `COGNITO_JWKS_URI=${jwksUri}`,
  ]);
  writeEnvFile('apps/frontend/.env.local', [
    'VITE_API_BASE_URL=/api',
    `VITE_COGNITO_USER_POOL_ID=${userPoolId}`,
    `VITE_COGNITO_CLIENT_ID=${clientId}`,
    'VITE_COGNITO_ENDPOINT=/cognito',
  ]);

  return { tableName, userPoolId, clientId, issuer, jwksUri };
}

// Allow running directly: `node tools/scripts/local-stack.mjs`.
if (import.meta.url === `file://${process.argv[1]}`) {
  prepareLocalStack()
    .then(() => log('local stack ready.'))
    .catch((err) => {
      console.error('\nlocal-stack failed:', err.message ?? err);
      process.exit(1);
    });
}
