// Seeds a user pool + public app client in the cognito-local emulator for fully-local dev.
//
// cognito-local supports only USER_PASSWORD_AUTH (no SRP), so the client is created with
// ALLOW_USER_PASSWORD_AUTH. IDs are generated by the emulator and persisted in its volume
// (apps/backend/.cognito), so this is idempotent — an existing pool/client is reused.
//
// Returns { userPoolId, clientId, issuer, jwksUri } for wiring into the local .env files.
// Usage (standalone): node tools/scripts/seed-cognito.mjs
// Also imported by tools/scripts/dev-local.mjs.

import {
  CognitoIdentityProviderClient,
  ListUserPoolsCommand,
  CreateUserPoolCommand,
  ListUserPoolClientsCommand,
  CreateUserPoolClientCommand,
} from '@aws-sdk/client-cognito-identity-provider';

const POOL_NAME = 'workboard-local';
const CLIENT_NAME = 'workboard-web';

/** @param {{ endpoint?: string, region?: string }} [opts] */
export async function seedCognito(opts = {}) {
  const endpoint = opts.endpoint ?? process.env.COGNITO_ENDPOINT ?? 'http://localhost:9229';
  const region = opts.region ?? process.env.AWS_REGION ?? 'us-east-1';

  const client = new CognitoIdentityProviderClient({
    endpoint,
    region,
    // The emulator ignores credentials but the SDK requires them to be present.
    credentials: { accessKeyId: 'local', secretAccessKey: 'local' },
  });

  try {
    // Find-or-create the user pool.
    const pools = await client.send(new ListUserPoolsCommand({ MaxResults: 60 }));
    let userPoolId = pools.UserPools?.find((p) => p.Name === POOL_NAME)?.Id;
    if (!userPoolId) {
      const created = await client.send(
        new CreateUserPoolCommand({
          PoolName: POOL_NAME,
          // Email is auto-verified via the emailed code (cognito-local uses the fixed CODE).
          AutoVerifiedAttributes: ['email'],
        }),
      );
      userPoolId = created.UserPool?.Id;
    }
    if (!userPoolId) throw new Error('cognito-local: failed to resolve a user pool id');

    // Find-or-create the public app client (no secret) with the password auth flow.
    const clients = await client.send(
      new ListUserPoolClientsCommand({ UserPoolId: userPoolId, MaxResults: 60 }),
    );
    let clientId = clients.UserPoolClients?.find((c) => c.ClientName === CLIENT_NAME)?.ClientId;
    if (!clientId) {
      const created = await client.send(
        new CreateUserPoolClientCommand({
          UserPoolId: userPoolId,
          ClientName: CLIENT_NAME,
          GenerateSecret: false,
          ExplicitAuthFlows: ['ALLOW_USER_PASSWORD_AUTH', 'ALLOW_REFRESH_TOKEN_AUTH'],
        }),
      );
      clientId = created.UserPoolClient?.ClientId;
    }
    if (!clientId) throw new Error('cognito-local: failed to resolve an app client id');

    const issuer = `${endpoint.replace(/\/$/, '')}/${userPoolId}`;
    const jwksUri = `${issuer}/.well-known/jwks.json`;
    return { userPoolId, clientId, issuer, jwksUri };
  } finally {
    client.destroy();
  }
}

// Allow running directly: `node tools/scripts/seed-cognito.mjs`
if (import.meta.url === `file://${process.argv[1]}`) {
  seedCognito()
    .then((r) => console.log('cognito-local seeded:', JSON.stringify(r, null, 2)))
    .catch((err) => {
      console.error('Failed to seed cognito-local:', err);
      process.exit(1);
    });
}
